### ISSUE TITLE
UI Text can be behind a 3D Object in Scene View

### ISSUE THREAD

**Issue by StinkySteak** [Delt06/toon-rp#111]
This is a demo space scene, I just add the text to it

![Screenshot_1](https://github.com/Delt06/toon-rp/assets/52377879/a9722753-636a-47e9-a220-f4b588a50539)

**Comment by Delt06** [comment]
I think this is expected behavior. I just did a test in URP, same thing happens there.
![image](https://github.com/Delt06/toon-rp/assets/32465621/25e7b326-d2cd-40ff-833c-4aff4e785d72)

**Comment by StinkySteak** [comment]
Damn, you are right. Thanks for confirming! 
Great work on the toon-rp, I'll keep watching on it
