### ISSUE TITLE
Skybox

### ISSUE THREAD

**Issue by einKnuffy** [Delt06/toon-rp#221]
How can you do a skybox material / shader graph with toon-rp as srp?

**Comment by Delt06** [comment]
Skybox shaders are typically compatible between render pipelines except they use some specific pipeline features. 
Thus, most skybox shaders should work correctly with Toon RP out of the box. You can use either a code-based shader or Toon RP unlit shader graph.

**Comment by einKnuffy** [comment]
Sounds good, but when creating a toon rp unlit shader you won't be able to set it as lightning environment (skybox) material. Could you elaborate on how to get support for the shader material as skybox material?

**Comment by Delt06** [comment]
You can, not via dragging and dropping it to the sky, but in the lighting settings. Afaik, that is the case for shader graph-based skyboxes in URP too.

**Comment by einKnuffy** [comment]
@Delt06 May you then give me an example for toon rp skybox shader code?

**Comment by einKnuffy** [comment]
Okay, I am sorry for misunderstanding you. I got it working, I had initially a wrong skybox shader that's why it did not work, but now I just changed some paramters like for the built-in render pipeline and it works. Thanks!

**Comment by Delt06** [comment]
Just in case, here's a sample code-based shader: https://gist.github.com/Delt06/50c2f298e02a6afdfb696bc0bb12f532
