### ISSUE TITLE
More control over outlines

### ISSUE THREAD

**Issue by BradFitz66** [Delt06/toon-rp#243]
I've got a game using toon-rp that has screen-space outlines enabled and I'm running into issues with it and grass. The grass needs to perfectly blend with the terrain, but the grass seemingly can either have outlines, or be in the transparent queue which causes it to not have outlines but will have outlines render above the grass

Grass with outlines:
![image](https://github.com/user-attachments/assets/74c4a1d2-c2cc-48e9-8d4c-849235b33c88)

Grass with render queue as overlay:
![image](https://github.com/user-attachments/assets/668acdb8-be6b-4e0d-a90e-f27e105a5d21)

Is there a way to have it so the grass doesn't have outlines, but still renders above other object's outlines? If no, could such a feature be implemented in the future?

**Comment by Delt06** [comment]
You can try using the outlines in the "After Opaque" mode: https://github.com/Delt06/toon-rp/wiki/Screen‐Space-Outline#after-opaque
It will also require keeping the grass in a transparent render queue.

**Comment by BradFitz66** [comment]
![image](https://github.com/user-attachments/assets/cafa8b24-d96c-47c3-be5a-8d3c97ec9c31)

That's better, but outlines that are against the grass end up thinner, causing this "blotchy" look, but it's good enough for now. Thanks!

**Comment by Delt06** [comment]
Glad to hear it worked.

Generally, I am not planning on improving screen-space outlines, as the RP focuses on inverted hull outlines. Dependening on the geometric complexity of your scene, you might wanna look into them instead, they provide many more settings, including per-layer filtering of what objects to have outlines, better thickness, etc.
